[package]
name = "systemd-parser"
description = "A nom parser for systemd unit files"
version = "0.1.3"
authors = ["Thomas Wickham <twickham@octo.com>"]
license = "MPL-2.0"

[dependencies]
quick-error = "^1.1"
itertools = "^0.5"

[dependencies.nom]
version = "^2.0"
features = ["verbose-errors"]



