[package]
name = "systemd-linter"
version = "0.1.0"
authors = ["Thomas Wickham <twickham@octo.com>"]

[dependencies]
systemd-parser = { version = "0.1.0", path = "./crates/systemd-parser" }
clap = "^2.20"

